# Generated by Django 4.1.2 on 2022-11-04 01:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_remove_usuario_matricula_usuario_email'),
        ('livro', '0011_alter_emprestimo_nome_alugado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprestimo',
            name='nome_alugado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='usuarios.usuario'),
        ),
    ]
