# Generated by Django 4.1.2 on 2022-11-04 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0013_alter_emprestimo_data_devolução_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emprestimo',
            name='tempo_alugado',
        ),
    ]
