# Generated by Django 4.1.2 on 2022-11-04 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0014_remove_emprestimo_tempo_alugado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livros',
            name='alugado',
            field=models.BooleanField(default=False),
        ),
    ]
