# Generated by Django 4.1.2 on 2022-11-09 14:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0022_alter_emprestimo_data_devolução_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprestimo',
            name='data_devolução',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 11, 11, 43, 30, 726689)),
        ),
        migrations.AlterField(
            model_name='emprestimo',
            name='data_emprestimo',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 9, 11, 43, 30, 726732)),
        ),
    ]
