# Generated by Django 4.1.2 on 2022-11-17 05:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0024_alter_emprestimo_data_devolução_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprestimo',
            name='data_devolução',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 19, 2, 14, 59, 757538)),
        ),
        migrations.AlterField(
            model_name='emprestimo',
            name='data_emprestimo',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 17, 2, 14, 59, 757581)),
        ),
    ]
