# Generated by Django 4.1.2 on 2022-11-17 06:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0025_alter_emprestimo_data_devolução_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='livros',
            name='img',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='emprestimo',
            name='data_devolução',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 19, 3, 11, 43, 798889)),
        ),
        migrations.AlterField(
            model_name='emprestimo',
            name='data_emprestimo',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 17, 3, 11, 43, 798934)),
        ),
    ]
