# Generated by Django 4.1.2 on 2022-11-27 17:26

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0027_alter_emprestimo_data_devolução_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='emprestimo',
            name='avaliacao',
        ),
        migrations.RemoveField(
            model_name='livros',
            name='alugado',
        ),
        migrations.RemoveField(
            model_name='livros',
            name='usuario',
        ),
        migrations.AddField(
            model_name='emprestimo',
            name='devolvido',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='emprestimo',
            name='reservado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='emprestimo',
            name='solicitado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='livros',
            name='estoque',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='emprestimo',
            name='data_devolução',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 4, 14, 26, 54, 21143)),
        ),
        migrations.AlterField(
            model_name='emprestimo',
            name='data_emprestimo',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 27, 14, 26, 54, 21253)),
        ),
    ]
