# Generated by Django 4.1.2 on 2022-10-29 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='email',
        ),
        migrations.AddField(
            model_name='usuario',
            name='matricula',
            field=models.CharField(default='1212131204', max_length=10),
        ),
    ]
