# Generated by Django 4.1.2 on 2022-10-29 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_remove_usuario_email_usuario_matricula'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='matricula',
        ),
        migrations.AddField(
            model_name='usuario',
            name='email',
            field=models.EmailField(default='victoroliveira104@gmail.com', max_length=254),
            preserve_default=False,
        ),
    ]
