# Generated by Django 4.1.2 on 2022-11-01 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_alter_usuario_matricula'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='matricula',
        ),
        migrations.AddField(
            model_name='usuario',
            name='email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
    ]
