# Generated by Django 4.1.2 on 2022-11-27 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0009_remove_usuario_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='aluno',
            field=models.BooleanField(default=False),
        ),
    ]
